# Site settings
title: Secure-Lee
email: info@secure-lee.com	
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Secure-Lee.com, where I talk about items of security interest, as well as my fitness interests. Since that's pretty much all I do these days, I figured it was best to combine the two. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://secure-lee.com" # the base hostname & protocol for your site
twitter_username: geekpixie
github_username:  geekpixie

# Build settings
markdown: kramdown
